"""Generate reference vectors from pywfrac for AirLAN's encoder/decoder tests.

pywfrac is the reference implementation the JavaScript port in wfrac.js follows. This
script asks it how it encodes a range of states and decodes the captured live frames,
and writes the answers to test/fixtures/pywfrac-vectors.json.

    pip install pywfrac==0.1.7
    python tools/gen_pywfrac_vectors.py
"""

import json
import random
from importlib.metadata import version
from pathlib import Path

from pywfrac.models.aircon import AirconStat
from pywfrac.parser import RacParser

ROOT = Path(__file__).resolve().parent.parent
FIXTURES = ROOT / "test" / "fixtures"

# pywfrac attribute -> AirLAN field
FIELDS = {
    "Operation": "power",
    "OperationMode": "mode",
    "PresetTemp": "presetTemp",
    "AirFlow": "airFlow",
    "WindDirectionUD": "windUD",
    "WindDirectionLR": "windLR",
    "Entrust": "entrust",
    "CoolHotJudge": "coolHotJudge",
    "ModelNr": "modelNr",
    "ModelNrRaw": "modelNrRaw",
    "Vacant": "vacant",
    "IsSelfCleanOperation": "selfClean",
}

parser = RacParser()


def decoded(frame: str, temperatures: bool = False) -> dict:
    """pywfrac's reading of a frame. Temperatures only for frames that carry the
    temperature segments: pywfrac reports a missing one as 0 degrees, AirLAN as None."""
    a = parser.translate_bytes(frame)
    out = {ours: getattr(a, theirs) for theirs, ours in FIELDS.items()}
    out["compressorRunning"] = a.CompressorRunning
    out["errorCode"] = None if a.ErrorCode == "00" else a.ErrorCode
    if temperatures:
        out["indoorTemp"] = a.IndoorTemp
        out["outdoorTemp"] = a.OutdoorTemp
    return out


def encoded(state: dict) -> str:
    stat = AirconStat()
    for theirs, ours in FIELDS.items():
        setattr(stat, theirs, state[ours])
    return parser.to_base64(stat)


def main() -> None:
    live = json.loads((FIXTURES / "live-frames.json").read_text())["frames"]
    decode_vectors = [{"frame": f["airconStat"], "state": decoded(f["airconStat"], temperatures=True)} for f in live.values()]

    base = {
        "power": False, "mode": 1, "presetTemp": 21.0, "airFlow": 0, "windUD": 0, "windLR": 0,
        "entrust": False, "coolHotJudge": True, "modelNr": 1, "modelNrRaw": 1, "vacant": False, "selfClean": False,
    }
    variations = {
        "power": [True, False],
        "mode": [0, 1, 2, 3, 4],
        "presetTemp": [16.0, 18.5, 20.0, 22.5, 25.0, 30.0],
        "airFlow": [0, 1, 2, 3, 4],
        "windUD": [0, 1, 2, 3, 4],
        "windLR": list(range(8)),
        "entrust": [True, False],
        "coolHotJudge": [True, False],
        "vacant": [True, False],
        "selfClean": [True, False],
    }
    states = [dict(base)]
    for field, values in variations.items():
        states += [{**base, field: v} for v in values]
    for model_nr, raw in [(0, 0), (1, 1), (2, 2), (2, 3)]:
        states += [{**base, "modelNr": model_nr, "modelNrRaw": raw, "vacant": True, "selfClean": True}]
    rng = random.Random(20261004)
    for _ in range(40):
        model_nr, raw = rng.choice([(0, 0), (1, 1), (2, 2), (2, 3)])
        states.append({
            "power": rng.random() < 0.5, "mode": rng.randrange(5), "presetTemp": rng.randrange(32, 61) / 2,
            "airFlow": rng.randrange(5), "windUD": rng.randrange(5), "windLR": rng.randrange(8),
            "entrust": rng.random() < 0.5, "coolHotJudge": rng.random() < 0.5,
            "modelNr": model_nr, "modelNrRaw": raw, "vacant": rng.random() < 0.5, "selfClean": rng.random() < 0.5,
        })
    # The states the app actually sends: a live frame with power/mode/setpoint changed.
    for f in live.values():
        current = decoded(f["airconStat"])
        sendable = {k: current[k] for k in base}
        for change in [{"power": True}, {"power": False}, {"mode": 1}, {"mode": 2}, {"presetTemp": 23.5}]:
            states.append({**sendable, **change})

    encode_vectors = []
    for s in states:
        frame = encoded(s)
        encode_vectors.append({"state": s, "frame": frame})
        decode_vectors.append({"frame": frame, "state": decoded(frame)})

    out = {
        "_comment": f"Generated by tools/gen_pywfrac_vectors.py from pywfrac {version('pywfrac')}. Do not edit by hand.",
        "encode": encode_vectors,
        "decode": decode_vectors,
    }
    (FIXTURES / "pywfrac-vectors.json").write_text(json.dumps(out, indent=1) + "\n")
    print(f"{len(encode_vectors)} encode and {len(decode_vectors)} decode vectors written")


if __name__ == "__main__":
    main()
